In [8]:
import requests
from dotenv import load_dotenv
import os
import pandas as pd
import rasterio
import numpy as np
import glob
import geopandas as gpd
from rasterstats import zonal_stats

load_dotenv('../envs/dev.env')

token = os.getenv("HCDP_API_TOKEN")
local_dep_dir = os.environ.get('DEPENDENCY_DIR')

headers = {
    "Authorization": f"Bearer {token}"
}

In [19]:
url = "https://api.hcdp.ikewai.org/mesonet/climate_report/rainfall_stats"
# rainfall_stats, temperature_stats, drought_stats, rainfall_historical, or temperature_historical
query_params = {
    "division_type": "island",
    "island": "Oʻahu",
    "startDate": "2026-01-01",
        "endDate": "2026-06-01"
}

# query_params = {
#     "division_type": "Statewide",
#     "startDate": "2026-01-01",
#     "endDate": "2026-05-01"
# }

# response = requests.get(url, params=query_params, headers=headers)

# print(response.json())
response = requests.get(url, params=query_params, headers=headers)

print(f"Status Code: {response.status_code}")
if response.status_code == 200:
    df_filtered = pd.DataFrame(response.json())
    display(df_filtered)
else:
    print(f"Response Text: {response.text}")

Status Code: 200

,island,division_type,name,date,mean,anomaly,pchange,rank,ytd_pnormal
0,Oʻahu,island,Oʻahu,2026-01-01T00:00:00.000Z,4.61,-0.13,-2.71,64,97
1,Oʻahu,island,Oʻahu,2026-02-01T00:00:00.000Z,9.87,5.32,116.86,12,156
2,Oʻahu,island,Oʻahu,2026-03-01T00:00:00.000Z,26.67,20.75,350.69,1,271
3,Oʻahu,island,Oʻahu,2026-04-01T00:00:00.000Z,6.62,2.46,59.17,25,247

In [40]:
response = requests.get(
    "https://api.hcdp.ikewai.org/mesonet/climate_report/rainfall_stats",
    params={"division_type": "island", "island": "Hawaiʻi"},
    headers=headers
)
df = pd.DataFrame(response.json())
print(df[["island","name","date"]].drop_duplicates().sort_values("date").tail(10))

       island     name                      date
1028  Hawaiʻi  Hawaiʻi  2025-08-01T00:00:00.000Z
1055  Hawaiʻi  Hawaiʻi  2025-09-01T00:00:00.000Z
946   Hawaiʻi  Hawaiʻi  2025-10-01T00:00:00.000Z
899   Hawaiʻi  Hawaiʻi  2025-11-01T00:00:00.000Z
1276  Hawaiʻi  Hawaiʻi  2025-12-01T00:00:00.000Z
1164  Hawaiʻi  Hawaiʻi  2026-01-01T00:00:00.000Z
1018  Hawaiʻi  Hawaiʻi  2026-02-01T00:00:00.000Z
1169  Hawaiʻi  Hawaiʻi  2026-03-01T00:00:00.000Z
1093  Hawaiʻi  Hawaiʻi  2026-04-01T00:00:00.000Z
1158  Hawaiʻi  Hawaiʻi  2026-05-01T00:00:00.000Z

In [23]:
payload = {
    "overwrite": True,
    "data": [["Oʻahu", "island", "Oʻahu", "2026-05-01", -9999, -9999, -9999, -9999, -9999]]
}
r = requests.post("https://api.hcdp.ikewai.org/mesonet/climate_report/rainfall_stats", json=payload, headers=headers)
print(r.status_code, r.text)

200 {"modified":1}

In [39]:
response = requests.get(
    "https://api.hcdp.ikewai.org/mesonet/climate_report/temperature_stats",
    params={"division_type": "island","name":"Oʻahu", "startDate": "2026-05-01"},
    headers=headers
)
df_filtered = pd.DataFrame(response.json())
display(df_filtered)

Empty DataFrame
Columns: []
Index: []

In [30]:
response = requests.get(
    "https://api.hcdp.ikewai.org/mesonet/climate_report/rainfall_stats",
    params={
        "division_type": "island",
        "island": "Oʻahu",
        "startDate": "2026-01-01"
    },
    headers=headers
)
df_filtered = pd.DataFrame(response.json())
display(df_filtered)

,island,division_type,name,date,mean,anomaly,pchange,rank,ytd_pnormal
0,Oʻahu,island,Oʻahu,2026-01-01T00:00:00.000Z,4.61,-0.13,-2.71,64,97
1,Oʻahu,island,Oʻahu,2026-02-01T00:00:00.000Z,9.87,5.32,116.86,12,156
2,Oʻahu,island,Oʻahu,2026-03-01T00:00:00.000Z,26.67,20.75,350.69,1,271
3,Oʻahu,island,Oʻahu,2026-04-01T00:00:00.000Z,6.62,2.46,59.17,25,247